version: '3.4'

services:
  redis:
    image: redis:latest
    ports:
    - "46379:6379"
    
  consul:
    image: consul:latest
    ports:
    - "48500:8500"

  carsharing:
    image: ${DOCKER_REGISTRY-}carsharing
    build:
      context: .
      dockerfile: src/Services/Carsharing/Dockerfile
    ports:
    - "4001:80"

  geocoding:
    image: ${DOCKER_REGISTRY-}geocoding
    build:
      context: .
      dockerfile: src/Services/Geocoding/Dockerfile
    ports:
    - "4002:80"      
      
  identity:
    image: ${DOCKER_REGISTRY-}identity
    build:
      context: .
      dockerfile: src/Services/Identity/Dockerfile
    ports:
    - "4003:80"  

  apigateway:
    image: ${DOCKER_REGISTRY-}apigateway
    build:
      context: .
      dockerfile: src/ApiGateway/Dockerfile
    ports:
    - "4000:80"

