version: '3.4'

services:
  carsharing:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"

  geocoding:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"


  identity:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"

